// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.2
// 	 protoc        v3.20.1
// source: cosmwasm/wasm/v1/_export.ts

export * from "./genesis";
export * from "./ibc";
export * from "./proposal";
export * from "./query";
export * from "./tx";
export * from "./types";
